### ISSUE TITLE
How to use Surrealdb in browser with Indexeddb?

### ISSUE THREAD

**Issue by LeonLiuY** [trifel/leptos_todo_app_surrealdb#1]
Hi, thanks for the example code.

I'm struggling to figure out how to skip running a server side Surrealdb, but instead start an embedded DB backed by Indexeddb and connect to it directly in the browser?

Appreciate if you can give some hints!

**Comment by trifel** [comment]
Hey, I really liked the idea of running this example with IndexedDB.

#2 

Thank you!
